name: mineral_redis
description: The redis module was designed exclusively for the Mineral framework.
version: 1.0.0

repository: https://github.com/mineral-dart/redis

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
