name: mineral_redis
description: The redis module was designed exclusively for the Mineral framework.
version: 1.0.0

repository: https://github.com/mineral-dart/redis

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  mineral_environment: ^1.0.1
  mineral_ioc: ^2.0.0
  mineral_package: ^1.1.0
  redis: ^3.1.0
